# Generated by Django 2.0.2 on 2018-11-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tpctest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('anhao', models.CharField(max_length=50)),
                ('idcard', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_pctest',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('usertel', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('psw', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
